import type { CatalogItem } from "./types";
import { MERCHANT_ID } from "./types";

/** Synthetic merchant catalog — agent-readable SKUs so the unique layer has something to buy. */
export const CATALOG: CatalogItem[] = [
  {
    sku: "RICE-BAS-1KG",
    name: "Aged Basmati Rice 1 kg",
    brand: "India Gate",
    category: "grains",
    pricePaise: 14200,
    unit: "1 kg",
    stock: 18,
    description: "Long-grain aged basmati, everyday cooking.",
  },
  {
    sku: "RICE-SON-5KG",
    name: "Sona Masoori 5 kg",
    brand: "Lal Qilla",
    category: "grains",
    pricePaise: 38900,
    unit: "5 kg",
    stock: 9,
    description: "Light everyday rice, south Indian staple.",
  },
  {
    sku: "ATA-WHL-5KG",
    name: "Whole Wheat Atta 5 kg",
    brand: "Aashirvaad",
    category: "grains",
    pricePaise: 27500,
    unit: "5 kg",
    stock: 14,
    description: "Chakki atta for rotis.",
  },
  {
    sku: "DAL-TOO-1KG",
    name: "Toor Dal 1 kg",
    brand: "Tata Sampann",
    category: "pulses",
    pricePaise: 16800,
    unit: "1 kg",
    stock: 22,
    description: "Unpolished toor dal.",
  },
  {
    sku: "DAL-MOO-500",
    name: "Moong Dal 500 g",
    brand: "Organic Tattva",
    category: "pulses",
    pricePaise: 9200,
    unit: "500 g",
    stock: 16,
    description: "Split yellow moong.",
  },
  {
    sku: "SPC-TUR-200",
    name: "Turmeric Powder 200 g",
    brand: "Everest",
    category: "spices",
    pricePaise: 6800,
    unit: "200 g",
    stock: 30,
    description: "Kitchen turmeric.",
  },
  {
    sku: "OIL-MUS-1L",
    name: "Mustard Oil 1 L",
    brand: "Fortune",
    category: "oil",
    pricePaise: 17800,
    unit: "1 L",
    stock: 11,
    description: "Kachi ghani mustard oil.",
  },
  {
    sku: "MIL-TON-1L",
    name: "Toned Milk 1 L",
    brand: "Amul",
    category: "dairy",
    pricePaise: 5600,
    unit: "1 L",
    stock: 40,
    description: "Chilled tetra pack.",
  },
  {
    sku: "GHI-AMU-500",
    name: "Cow Ghee 500 ml",
    brand: "Amul",
    category: "dairy",
    pricePaise: 32500,
    unit: "500 ml",
    stock: 7,
    description: "Clarified butter.",
  },
  {
    sku: "SNK-BHA-200",
    name: "Bhujia 200 g",
    brand: "Haldiram's",
    category: "snacks",
    pricePaise: 5500,
    unit: "200 g",
    stock: 25,
    description: "Namkeen snack mix.",
  },
  {
    sku: "SNK-CHO-90",
    name: "Milk Chocolate 90 g",
    brand: "Cadbury",
    category: "snacks",
    pricePaise: 8000,
    unit: "90 g",
    stock: 20,
    description: "Not a grocery staple — used to demo semantic mismatch.",
  },
  {
    sku: "TEA-TAT-250",
    name: "Tea Leaf 250 g",
    brand: "Tata Tea",
    category: "beverages",
    pricePaise: 11500,
    unit: "250 g",
    stock: 19,
    description: "CTC leaf tea.",
  },
  {
    sku: "HSE-DET-1KG",
    name: "Detergent Powder 1 kg",
    brand: "Surf Excel",
    category: "household",
    pricePaise: 14900,
    unit: "1 kg",
    stock: 12,
    description: "Laundry powder.",
  },
];

export function getItem(sku: string) {
  return CATALOG.find((i) => i.sku === sku) ?? null;
}

export function merchantMeta() {
  return {
    id: MERCHANT_ID,
    name: "Nila Kirana",
    city: "Bengaluru",
    note: "Synthetic catalog — agent-readable SKUs only. Not a live storefront.",
  };
}
