import type { CatalogItem } from "./types";
import { MERCHANT_ID } from "./types";

/** ElectroCore Tech & Electronics Catalog with rich technical specifications */
export const TECH_CATALOG: CatalogItem[] = [
  {
    sku: "SONY-WH1000XM5",
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    category: "audio",
    pricePaise: 2999000,
    unit: "1 unit",
    stock: 8,
    description: "Industry-leading active noise cancellation with 8 microphones, Auto NC Optimizer, and 30-hour battery life.",
    imageEmoji: "🎧",
    rating: 4.8,
    tags: ["audio", "anc", "bluetooth", "30h-battery", "ldac", "wireless"],
    isFeatured: true,
    specs: {
      price: "₹29,990",
      availability: "In stock (8)",
      connectivity: "Bluetooth 5.2 / LDAC / 3.5mm",
      brand: "Sony",
      batteryHours: 30,
      weightGrams: 250,
      driverMm: 30,
      noiseCancellation: "Industry-leading Dual Chip ANC",
      fastCharge: "3 min = 3 hrs",
      microphones: "8 beamforming mics",
      warranty: "1 Year Official Sony India",
    },
  },
  {
    sku: "LOGI-MX-MASTER-3S",
    name: "Logitech MX Master 3S Mouse",
    brand: "Logitech",
    category: "peripherals",
    pricePaise: 999000,
    unit: "1 unit",
    stock: 0, // Out of stock (matches screenshot 4!)
    description: "Ergonomic wireless performance mouse with 8K DPI track-on-glass sensor and Quiet Click switches.",
    imageEmoji: "🖱️",
    rating: 4.9,
    tags: ["mouse", "peripherals", "8k-dpi", "70d-battery", "quiet-click"],
    isFeatured: true,
    specs: {
      price: "₹9,990",
      availability: "Out of stock",
      connectivity: "Bluetooth Low Energy / Logi Bolt",
      brand: "Logitech",
      dpi: 8000,
      batteryDays: 70,
      weightGrams: 141,
      keys: "7 custom programmable buttons",
      scrollWheel: "MagSpeed Electromagnetic (1000 lines/sec)",
      charging: "USB-C quick charge",
    },
  },
  {
    sku: "KEYCHRON-K3-MAX",
    name: "Keychron K3 Max Wireless Keyboard",
    brand: "Keychron",
    category: "peripherals",
    pricePaise: 1649000,
    unit: "1 unit",
    stock: 12,
    description: "Ultra-slim 75% layout custom wireless mechanical keyboard with 2.4 GHz, Bluetooth 5.1, and QMK/VIA support.",
    imageEmoji: "⌨️",
    rating: 4.7,
    tags: ["keyboard", "peripherals", "mechanical", "rgb", "qmk-via", "wireless"],
    isFeatured: true,
    specs: {
      price: "₹16,490",
      availability: "In stock (12)",
      connectivity: "2.4 GHz / Bluetooth 5.1 / Type-C",
      brand: "Keychron",
      keys: 84,
      backlight: "RGB customizable",
      batteryHours: 40,
      weightGrams: 525,
      switches: "Low-profile Gateron Mechanical Hot-Swappable",
      layout: "Ultra-slim 75% Compact",
    },
  },
  {
    sku: "ANKER-7IN1-HUB",
    name: "Anker 7-in-1 USB-C Hub",
    brand: "Anker",
    category: "accessories",
    pricePaise: 499000,
    unit: "1 unit",
    stock: 14,
    description: "7-in-1 hub with HDMI 4K60Hz, 2x USB-A 5Gbps, SD/microSD card slots, and 100W Power Delivery pass-through.",
    imageEmoji: "🔌",
    rating: 4.8,
    tags: ["usb-c", "hdmi: 4k60", "ports: 7", "sdSlots: 2", "100w-pd"],
    isFeatured: true,
    specs: {
      price: "₹4,990",
      availability: "In stock (14)",
      connectivity: "USB-C Thunderbolt 3/4 compatible",
      brand: "Anker",
      ports: 7,
      powerDeliveryW: 100,
      hdmiResolution: "4K @ 60Hz HDR",
      sdSlots: 2,
      usbSpeed: "5 Gbps High Speed",
      material: "Precision Aluminum Alloy",
    },
  },
  {
    sku: "ANKER-POWERCORE-20K",
    name: "Anker PowerCore 20000mAh Power Bank",
    brand: "Anker",
    category: "power",
    pricePaise: 399000,
    unit: "1 unit",
    stock: 40,
    description: "High-capacity portable charger with 22.5W high-speed charging for phones, tablets, and wireless earbuds.",
    imageEmoji: "🔋",
    rating: 4.7,
    tags: ["powerbank", "20000mah", "22.5w", "usb-c", "power"],
    isFeatured: true,
    specs: {
      price: "₹3,990",
      availability: "In stock (40)",
      connectivity: "USB-C In/Out + 2x USB-A Out",
      brand: "Anker",
      capacityMah: 20000,
      outputW: 22.5,
      weightGrams: 345,
      fastCharge: "PowerIQ 3.0 & Quick Charge 3.0",
      rechargeTimeHours: 4.5,
    },
  },
  {
    sku: "ANKER-USBC-100W-1M",
    name: "Anker USB-C to USB-C 100W Cable (1m)",
    brand: "Anker",
    category: "cables",
    pricePaise: 149000,
    unit: "1 unit",
    stock: 60,
    description: "Braided 100W USB-C cable for laptops, power banks, and smartphones with E-Marker chip safety.",
    imageEmoji: "⚡",
    rating: 4.9,
    tags: ["cable", "usb-c", "power: 100w", "length: 1m", "braided"],
    isFeatured: true,
    specs: {
      price: "₹1,490",
      availability: "In stock (60)",
      connectivity: "USB-C to USB-C (E-Marker Chip)",
      brand: "Anker",
      powerW: 100,
      lengthMeters: 1,
      dataSpeed: "480 Mbps USB 2.0",
      material: "Double-braided Nylon Shield",
      bendLifespan: "25,000+ bends tested",
    },
  },
  {
    sku: "JBL-FLIP-6",
    name: "JBL Flip 6 Portable Bluetooth Speaker",
    brand: "JBL",
    category: "audio",
    pricePaise: 999900,
    unit: "1 unit",
    stock: 18,
    description: "Bold JBL Original Pro Sound with 2-way speaker system, racetrack woofer, and IP67 waterproof/dustproof.",
    imageEmoji: "🔊",
    rating: 4.6,
    tags: ["audio", "speaker", "bluetooth", "ip67", "portable"],
    isFeatured: true,
    specs: {
      price: "₹9,999",
      availability: "In stock (18)",
      connectivity: "Bluetooth 5.1",
      brand: "JBL",
      outputW: 30,
      batteryHours: 12,
      waterResistance: "IP67 Waterproof & Dustproof",
      weightGrams: 550,
      partyBoost: "Pair multiple compatible speakers",
    },
  },
  {
    sku: "APPLE-AIRPODS-PRO-2",
    name: "Apple AirPods Pro (2nd Gen)",
    brand: "Apple",
    category: "audio",
    pricePaise: 2490000,
    unit: "1 unit",
    stock: 15,
    description: "Up to 2x more Active Noise Cancellation, Adaptive Audio, Personalized Spatial Audio, and USB-C MagSafe case.",
    imageEmoji: "🎵",
    rating: 4.9,
    tags: ["audio", "earbuds", "anc", "apple-h2", "spatial-audio"],
    isFeatured: true,
    specs: {
      price: "₹24,900",
      availability: "In stock (15)",
      connectivity: "Bluetooth 5.3 / Apple H2 Chip",
      brand: "Apple",
      batteryHours: 30,
      noiseCancellation: "Pro-grade Active Noise Cancellation",
      charging: "MagSafe USB-C / Qi Wireless",
      waterResistance: "IP54 Sweat & Water Resistant",
    },
  },
  {
    sku: "SAMSUNG-T7-1TB",
    name: "Samsung T7 Shield 1TB Portable SSD",
    brand: "Samsung",
    category: "storage",
    pricePaise: 1049900,
    unit: "1 unit",
    stock: 22,
    description: "Rugged durability with IP65 rating, transfer speeds up to 1,050 MB/s, and 3-meter drop resistance.",
    imageEmoji: "💾",
    rating: 4.8,
    tags: ["storage", "ssd", "1tb", "1050mbs", "ip65", "rugged"],
    isFeatured: true,
    specs: {
      price: "₹10,499",
      availability: "In stock (22)",
      connectivity: "USB 3.2 Gen 2 (10Gbps)",
      brand: "Samsung",
      capacity: "1 TB NVMe",
      readSpeedMbS: 1050,
      writeSpeedMbS: 1000,
      durability: "IP65 Water/Dust + 3m Drop Resistance",
      weightGrams: 98,
    },
  },
  {
    sku: "DELL-U2723QE-4K",
    name: "Dell UltraSharp 27\" 4K USB-C Hub Monitor",
    brand: "Dell",
    category: "peripherals",
    pricePaise: 4299000,
    unit: "1 unit",
    stock: 6,
    description: "27-inch 4K UHD IPS Black monitor with 90W USB-C power delivery, RJ45 Ethernet, and 98% DCI-P3 color gamut.",
    imageEmoji: "🖥️",
    rating: 4.9,
    tags: ["monitor", "4k", "ips-black", "90w-usbc", "peripherals"],
    isFeatured: true,
    specs: {
      price: "₹42,990",
      availability: "In stock (6)",
      connectivity: "USB-C 90W PD, HDMI 2.0, DP 1.4, RJ45",
      brand: "Dell",
      resolution: "4K UHD (3840 x 2160) @ 60Hz",
      panelType: "IPS Black (2000:1 Contrast)",
      colorGamut: "98% DCI-P3, 100% sRGB",
      usbPorts: "5x USB-A 10Gbps Hub",
    },
  },
];

/** Grocery SKUs for unit tests and fallback compatibility */
export const GROCERY_CATALOG: CatalogItem[] = [
  {
    sku: "RICE-BAS-1KG",
    name: "Aged Basmati Rice 1 kg",
    brand: "India Gate",
    category: "grains",
    pricePaise: 14200,
    unit: "1 kg",
    stock: 18,
    description: "Long-grain aged basmati, everyday cooking.",
  },
  {
    sku: "RICE-BAS-5KG",
    name: "Aged Basmati Rice 5 kg (Economy Pack)",
    brand: "India Gate",
    category: "grains",
    pricePaise: 62500,
    unit: "5 kg",
    stock: 10,
    description: "Long-grain aged basmati in bulk economy pack (₹125/kg).",
  },
  {
    sku: "RICE-SON-5KG",
    name: "Sona Masoori 5 kg",
    brand: "Lal Qilla",
    category: "grains",
    pricePaise: 38900,
    unit: "5 kg",
    stock: 9,
    description: "Light everyday rice, south Indian staple.",
  },
  {
    sku: "ATA-WHL-5KG",
    name: "Whole Wheat Atta 5 kg",
    brand: "Aashirvaad",
    category: "grains",
    pricePaise: 27500,
    unit: "5 kg",
    stock: 14,
    description: "Chakki atta for rotis.",
  },
  {
    sku: "DAL-TOO-1KG",
    name: "Toor Dal 1 kg",
    brand: "Tata Sampann",
    category: "pulses",
    pricePaise: 16800,
    unit: "1 kg",
    stock: 22,
    description: "Unpolished toor dal.",
  },
  {
    sku: "DAL-MOO-500",
    name: "Moong Dal 500 g",
    brand: "Organic Tattva",
    category: "pulses",
    pricePaise: 9200,
    unit: "500 g",
    stock: 16,
    description: "Split yellow moong.",
  },
  {
    sku: "SPC-TUR-200",
    name: "Turmeric Powder 200 g",
    brand: "Everest",
    category: "spices",
    pricePaise: 6800,
    unit: "200 g",
    stock: 30,
    description: "Kitchen turmeric.",
  },
  {
    sku: "OIL-MUS-1L",
    name: "Mustard Oil 1 L",
    brand: "Fortune",
    category: "oil",
    pricePaise: 17800,
    unit: "1 L",
    stock: 11,
    description: "Kachi ghani mustard oil.",
  },
  {
    sku: "MIL-TON-1L",
    name: "Toned Milk 1 L",
    brand: "Amul",
    category: "dairy",
    pricePaise: 5600,
    unit: "1 L",
    stock: 40,
    description: "Chilled tetra pack.",
  },
  {
    sku: "GHI-AMU-500",
    name: "Cow Ghee 500 ml",
    brand: "Amul",
    category: "dairy",
    pricePaise: 32500,
    unit: "500 ml",
    stock: 7,
    description: "Clarified butter.",
  },
  {
    sku: "SNK-BHA-200",
    name: "Bhujia 200 g",
    brand: "Haldiram's",
    category: "snacks",
    pricePaise: 5500,
    unit: "200 g",
    stock: 25,
    description: "Namkeen snack mix.",
  },
  {
    sku: "SNK-CHO-90",
    name: "Milk Chocolate 90 g",
    brand: "Cadbury",
    category: "snacks",
    pricePaise: 8000,
    unit: "90 g",
    stock: 20,
    description: "Not a grocery staple — used to demo semantic mismatch.",
  },
  {
    sku: "TEA-TAT-250",
    name: "Tea Leaf 250 g",
    brand: "Tata Tea",
    category: "beverages",
    pricePaise: 11500,
    unit: "250 g",
    stock: 19,
    description: "CTC leaf tea.",
  },
  {
    sku: "HSE-DET-1KG",
    name: "Detergent Powder 1 kg",
    brand: "Surf Excel",
    category: "household",
    pricePaise: 14900,
    unit: "1 kg",
    stock: 12,
    description: "Laundry powder.",
  },
];

/** Combined catalog */
export const CATALOG: CatalogItem[] = [...TECH_CATALOG, ...GROCERY_CATALOG];

export function getItem(sku: string) {
  return CATALOG.find((i) => i.sku === sku) ?? null;
}

export function merchantMeta() {
  return {
    id: MERCHANT_ID,
    name: "SafeBuy Store",
    city: "Bengaluru",
    note: "Bounded AI Buyer · Grounded Razorpay Test Mode storefront.",
  };
}

